version: 2
services:
  - type: web
    name: loan-origination-api
    env: python
    plan: starter
    rootDir: backend
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r backend/requirements-prod-norust.txt
    startCommand: gunicorn backend/app_hardened:app --chdir backend --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
