version: 2
services:
  - type: web
    name: loan-origination-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fastapi_app:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://loan-origination.netlify.app
