version: 2
services:
  - type: web
    name: loan-origination-api
    env: python
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements-minimal.txt
    startCommand: gunicorn app_minimal:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
